### ISSUE TITLE
Data type of HISTORY_PREVIOUS_VALUE

### ISSUE THREAD

**Issue by MarkIggy** [euroargodev/ArgoNetCDF#11]
In the FileChecker,  HISTORY_PREVIOUS_VALUE is type float in all of the file types except Bio-profile.  In Bio-profile, either float or double is accepted.  I don't remember the history of this.

My question: What should we enforce for traj-v3.2?

(I am currently only allowing float but Jean-Philippe uses double in some or all of his v3.2 files.)

**Comment by apswong** [comment]
Hi @MarkIggy.  I believe "double" is needed in bgc files because some bgc parameters need 64bit storage. e.g. radiometry counts.  The data type of each parameter is noted in the parameters xlsx, which @catsch maintains.  The GDAC file checker should be synched with the parameters xlsx.

Since traj-v3.2 is designed to hold both core and bgc parameters, HISTORY_PREVIOUS_VAUE in traj-v3.2 should accommodate both float and double values.  Most floats will only require "float", but some bgc floats will require "double".

**Comment by MarkIggy** [comment]
This issue was implemented in v2.8.00.
HISTORY_PREVIOUS_VALUE may be either float or double in traj-v3.2
